// SPX intraday expected-move cone.
//
// Phase-5 model (calibrated + OOS-validated on 771 RTH days 2023-05..2026-06 and
// real 0DTE option data 2024-01..2026-04 — see `AI STUFF/analysis/expected_move_cone/`
// JOURNAL.md Phase 5, harness `phase5_calibrate.py`):
//
//   half_side(k, elapsed) = M_side(k) * S_close * sqrt(varianceShare(anchor, elapsed))
//
// 1. ACCRUAL — intraday variance does NOT accrue linearly in clock time (the open is
//    ~2.5x hotter per minute than lunch). `CONE_VARIANCE_CUM` is the measured cumulative
//    variance share by minute-of-session; the old linear-sqrt(t) cone was ~25% too narrow
//    (in variance) anchored at the open and ~15-25% too wide midday.
// 2. SCALE — per-day implied scale from the live 0DTE credits (kind:"implied") is the
//    best available predictor of the remaining session (Spearman 0.88 vs realized; the
//    first-30-min-RV proxy manages 0.75, a static prior 0.60). Fallback: the per-time-of-
//    day prior measured in Phase 0 (kind:"prior").
// 3. CALIBRATION — credit-implied scales carry a variance risk premium (~6% wide) and the
//    realized distribution is crash-skewed (left tail fat, right tail thin). For the
//    implied kind each level k maps to per-side multipliers M_dn/M_up = bias x empirical
//    z-quantile (train <= 2025-09-30; held OOS 2025-10..2026-06: 1.645-sigma band covers
//    ~90% with balanced ~5%/5% breaches, vs 85-89% down-heavy for the old model).
//    The prior kind keeps symmetric Gaussian k — median-|z| bias correction is WRONG for
//    an unconditional scale (it recentres on the median day and abandons the tails).
//
// Levels: 1, 1.645 (the ~0.05-delta short-strike "frontier"), 2 — these are the chart's
// level KEYS; the implied kind's actual half-widths apply the calibrated multipliers.

import { DEFAULT_WIDTH, impliedScale, signedDistanceToLoss, type SpreadSide } from "./spreadResponse";

export const CONE_DEFAULT_LEVELS = [1, 1.645, 2] as const;
// Measured global diffusion coefficient (pts/sqrt-min), 745 days 2023-05 .. 2026-05.
export const CONE_PRIOR_A = 2.1;
// Per-time-of-day A keyed by minutes-to-close (16:00 ET). The open is the hottest part of
// the session; the prior interpolates this curve. From backtest_cone.py (Phase 0).
const PRIOR_A_BY_MTC: ReadonlyArray<readonly [number, number]> = [
  [60, 1.87], // 15:00
  [120, 1.75], // 14:00
  [180, 2.14], // 13:00
  [240, 1.94], // 12:00
  [300, 2.02], // 11:00
  [360, 2.19], // 10:00
  [390, 2.38], // 09:30
];

// ---- Phase-5 calibrated constants (generated by phase5_calibrate.py export) ----
// Fit: train <= 2025-09-30, FPL credit-implied scale, 2165 day-anchor rows;
// OOS-validated 2025-10 .. 2026-06.
export const CONE_SESSION_MINUTES = 390;
// Cumulative intraday variance share by minute-of-session (close-to-close 1-min returns,
// per-day normalized, cross-day median; 771 full days 2023-05-02 .. 2026-06-09).
// Index i = session minute of the bar CLOSE (0 = 09:31, 389 = 16:00); value = share of a
// typical day's 09:31->16:00 variance realized by that minute. Regenerate via
// `phase5_calibrate.py export` — do not hand-edit.
const CONE_VARIANCE_CUM: readonly number[] = [0.000000, 0.012087, 0.020553, 0.027657, 0.033911, 0.039423, 0.045019, 0.050417, 0.055348, 0.060206, 0.066670, 0.072061, 0.077359, 0.082837, 0.088516, 0.094222, 0.099762, 0.105497, 0.111159, 0.116656, 0.122134, 0.127618, 0.132812, 0.137550, 0.142190, 0.146595, 0.150801, 0.155032, 0.160732, 0.166656, 0.172987, 0.179602, 0.186297, 0.191523, 0.196728, 0.201550, 0.206321, 0.211063, 0.215842, 0.220414, 0.225270, 0.230148, 0.234867, 0.239442, 0.243860, 0.247859, 0.251658, 0.255372, 0.259187, 0.263069, 0.267034, 0.271078, 0.275326, 0.279505, 0.283537, 0.287396, 0.291364, 0.295155, 0.299006, 0.302844, 0.306767, 0.310535, 0.314339, 0.317988, 0.321711, 0.325537, 0.329277, 0.332981, 0.336685, 0.340210, 0.343605, 0.347052, 0.350459, 0.353773, 0.357237, 0.360724, 0.364036, 0.367371, 0.370825, 0.374142, 0.377282, 0.380336, 0.383255, 0.386008, 0.388677, 0.391286, 0.393937, 0.396533, 0.399335, 0.402245, 0.405268, 0.408317, 0.411364, 0.414129, 0.416809, 0.419616, 0.422314, 0.424983, 0.427729, 0.430403, 0.432898, 0.435388, 0.437900, 0.440345, 0.442862, 0.445314, 0.447744, 0.450156, 0.452535, 0.454835, 0.457203, 0.459528, 0.461924, 0.464255, 0.466540, 0.468763, 0.471055, 0.473271, 0.475687, 0.478208, 0.480698, 0.483144, 0.485615, 0.487928, 0.490232, 0.492601, 0.494990, 0.497318, 0.499663, 0.501878, 0.504063, 0.506255, 0.508424, 0.510450, 0.512497, 0.514450, 0.516378, 0.518214, 0.520234, 0.522290, 0.524392, 0.526485, 0.528669, 0.530637, 0.532562, 0.534465, 0.536296, 0.538095, 0.540205, 0.542276, 0.544373, 0.546568, 0.548815, 0.550773, 0.552740, 0.554691, 0.556582, 0.558454, 0.560391, 0.562294, 0.564201, 0.566056, 0.567819, 0.569533, 0.571221, 0.572849, 0.574479, 0.576154, 0.577813, 0.579506, 0.581280, 0.583184, 0.585133, 0.587095, 0.589053, 0.590889, 0.592614, 0.594252, 0.595948, 0.597655, 0.599423, 0.601209, 0.603034, 0.604747, 0.606415, 0.608088, 0.609782, 0.611425, 0.613109, 0.614797, 0.616422, 0.618012, 0.619596, 0.621184, 0.622790, 0.624427, 0.626074, 0.627780, 0.629511, 0.631306, 0.633126, 0.634901, 0.636623, 0.638257, 0.639799, 0.641256, 0.642715, 0.644201, 0.645863, 0.647662, 0.649664, 0.651731, 0.653838, 0.655856, 0.657825, 0.659648, 0.661466, 0.663242, 0.665042, 0.666766, 0.668505, 0.670179, 0.671865, 0.673500, 0.675146, 0.676736, 0.678350, 0.679931, 0.681562, 0.683213, 0.684902, 0.686647, 0.688426, 0.690166, 0.691846, 0.693481, 0.695071, 0.696644, 0.698409, 0.700220, 0.702054, 0.703906, 0.705771, 0.707407, 0.708994, 0.710622, 0.712222, 0.713841, 0.715463, 0.717112, 0.718737, 0.720341, 0.721922, 0.723482, 0.725067, 0.726648, 0.728256, 0.729825, 0.731483, 0.733067, 0.734660, 0.736206, 0.737778, 0.739297, 0.740784, 0.742229, 0.743675, 0.745078, 0.746627, 0.748270, 0.750114, 0.752028, 0.754045, 0.755982, 0.757928, 0.759797, 0.761636, 0.763396, 0.765117, 0.766787, 0.768412, 0.770058, 0.771746, 0.773463, 0.775225, 0.776911, 0.778595, 0.780278, 0.781926, 0.783586, 0.785345, 0.787128, 0.788904, 0.790675, 0.792346, 0.793982, 0.795567, 0.797141, 0.798873, 0.800728, 0.802535, 0.804362, 0.806168, 0.807816, 0.809375, 0.810970, 0.812549, 0.814145, 0.815715, 0.817332, 0.818934, 0.820542, 0.822137, 0.823765, 0.825335, 0.826899, 0.828471, 0.830005, 0.831538, 0.833101, 0.834683, 0.836266, 0.837876, 0.839514, 0.841130, 0.842734, 0.844320, 0.845915, 0.847807, 0.849872, 0.851974, 0.854114, 0.856283, 0.858126, 0.859868, 0.861559, 0.863214, 0.864864, 0.866526, 0.868164, 0.869790, 0.871434, 0.873104, 0.874809, 0.876485, 0.878219, 0.879957, 0.881685, 0.883382, 0.885122, 0.886853, 0.888597, 0.890364, 0.892147, 0.893845, 0.895471, 0.897077, 0.898662, 0.900492, 0.902415, 0.904521, 0.906682, 0.908913, 0.910964, 0.913046, 0.915052, 0.917065, 0.919047, 0.921034, 0.923015, 0.925064, 0.927145, 0.929320, 0.931653, 0.934030, 0.936434, 0.938898, 0.941433, 0.946074, 0.951074, 0.956263, 0.961640, 0.967819, 0.972512, 0.976964, 0.981355, 0.985571, 0.990438, 0.994944, 1.000000];
// Per-side level multipliers for the IMPLIED scale kind (= bias x empirical z-quantile):
// variance-risk-premium correction + crash skew in one step. Keys match CONE_DEFAULT_LEVELS.
const CONE_IMPLIED_K_DOWN: ReadonlyMap<number, number> = new Map([
  [1, 0.8454],
  [1.645, 1.6868],
  [2, 2.1802],
]);
const CONE_IMPLIED_K_UP: ReadonlyMap<number, number> = new Map([
  [1, 0.9649],
  [1.645, 1.595],
  [2, 1.8427],
]);

export type ConeScale =
  | { kind: "implied"; s0: number; sourceMinutesToClose: number } // day move-scale at the anchor (index pts)
  | { kind: "prior"; a?: number }; // a defaults to the time-of-day prior

export type ConeLevelPoint = {
  minutesToClose: number;
  elapsedMinutes: number;
  upper: number;
  lower: number;
  half: number; // mean of the two side half-widths (kept for back-compat)
  halfUp: number;
  halfDown: number;
};

export type ConeLevel = { k: number; points: ConeLevelPoint[] };

export type ExpectedMoveCone = {
  anchorSpot: number;
  anchorMinutesToClose: number;
  rate: number; // S_close / sqrt(mtc) — kept for back-compat with the old linear model
  scaleKind: "implied" | "prior";
  sAtClose: number; // 1-sigma scale at 16:00 (pre-multiplier)
  closeRange: { upper: number; lower: number; half: number }; // k=1 band at the close
  levels: ConeLevel[];
};

/** Time-of-day prior rate r (pts/sqrt-min) by minutes-to-close, interpolated + clamped. */
export function priorRate(minutesToClose: number): number {
  const mtc = Math.max(minutesToClose, 0);
  const t = PRIOR_A_BY_MTC;
  if (mtc <= t[0][0]) return t[0][1];
  if (mtc >= t[t.length - 1][0]) return t[t.length - 1][1];
  for (let i = 1; i < t.length; i++) {
    if (mtc <= t[i][0]) {
      const [m0, a0] = t[i - 1];
      const [m1, a1] = t[i];
      return a0 + ((a1 - a0) * (mtc - m0)) / (m1 - m0);
    }
  }
  return CONE_PRIOR_A;
}

/** Linear interpolation into CONE_VARIANCE_CUM at a fractional session-minute index. */
function varianceCumAt(index: number): number {
  const last = CONE_VARIANCE_CUM.length - 1;
  const x = Math.min(Math.max(index, 0), last);
  const i = Math.floor(x);
  if (i >= last) return CONE_VARIANCE_CUM[last];
  const frac = x - i;
  return CONE_VARIANCE_CUM[i] + (CONE_VARIANCE_CUM[i + 1] - CONE_VARIANCE_CUM[i]) * frac;
}

/**
 * Share of the anchor->close variance realized `elapsed` minutes after an anchor placed
 * `anchorMinutesToClose` before the close. 0 at the anchor, 1 at the close. Uses the
 * measured intraday profile for a regular 390-minute session; falls back to linear
 * accrual for other session lengths (half-days) where the profile was not fit.
 *
 * Anchors EARLIER than the profiled session (mtc > 389, e.g. a 09:30:00 wall clock or
 * pre-market) clamp to the open: the share stays 0 until the elapsed grid reaches the
 * open, then accrues on the profile. That is the correct RTH-only semantics — the chart
 * and the profile both cover 09:30-16:00, and no RTH variance accrues before the open.
 */
export function varianceShare(anchorMinutesToClose: number, elapsed: number, sessionMinutes: number = CONE_SESSION_MINUTES): number {
  const mtc = Math.max(anchorMinutesToClose, 0);
  const e = Math.min(Math.max(elapsed, 0), mtc);
  if (mtc <= 0) return 0;
  if (sessionMinutes !== CONE_SESSION_MINUTES) {
    return e / mtc; // unprofiled session shape — honest linear fallback
  }
  const last = CONE_VARIANCE_CUM.length - 1; // = close index
  const anchorIdx = last - mtc;
  const wAnchor = varianceCumAt(anchorIdx);
  const denom = CONE_VARIANCE_CUM[last] - wAnchor;
  if (denom <= 0) return e >= mtc ? 1 : 0;
  return (varianceCumAt(anchorIdx + e) - wAnchor) / denom;
}

function impliedSideK(level: number, side: "up" | "down"): number {
  const table = side === "up" ? CONE_IMPLIED_K_UP : CONE_IMPLIED_K_DOWN;
  // Uncalibrated custom levels degrade to the symmetric Gaussian k.
  return table.get(level) ?? level;
}

/** 1-sigma scale to the close (index pts) for the given anchor, before level multipliers. */
function scaleAtClose(scale: ConeScale, anchorMinutesToClose: number, sessionMinutes: number): number {
  const mtc = Math.max(anchorMinutesToClose, 0);
  if (scale.kind === "implied") {
    const src = Math.max(scale.sourceMinutesToClose, 0.5);
    if (Number.isFinite(scale.s0) && scale.s0 > 0) {
      if (Math.abs(src - mtc) < 1e-9) return scale.s0;
      // Re-anchor an implied scale quoted at a different horizon through the profile:
      // remaining-variance ratio between the two anchors.
      const last = CONE_VARIANCE_CUM.length - 1;
      const rem = (m: number) => Math.max(CONE_VARIANCE_CUM[last] - varianceCumAt(last - Math.max(m, 0)), 0);
      const ratio = sessionMinutes === CONE_SESSION_MINUTES && rem(src) > 0 ? rem(mtc) / rem(src) : mtc / src;
      return scale.s0 * Math.sqrt(Math.max(ratio, 0));
    }
    return priorRate(mtc) * Math.sqrt(mtc);
  }
  const a = scale.a != null && scale.a > 0 ? scale.a : priorRate(mtc);
  return a * Math.sqrt(mtc);
}

/**
 * Build the expected-move cone from an anchor (spot + minutes-to-close) and a scale.
 * Points run from the anchor (elapsed 0, half 0) forward to the close on a `stepMinutes`
 * grid. Pure / time-agnostic — the chart layer maps each point's elapsed to a bar epoch.
 */
export function expectedMoveCone(input: {
  anchorSpot: number;
  anchorMinutesToClose: number;
  scale: ConeScale;
  levels?: number[];
  stepMinutes?: number;
  sessionMinutes?: number;
}): ExpectedMoveCone {
  const mtc = Math.max(input.anchorMinutesToClose, 0);
  const step = Math.max(input.stepMinutes ?? 2, 0.5);
  const session = input.sessionMinutes ?? CONE_SESSION_MINUTES;
  const levels = (input.levels ?? [...CONE_DEFAULT_LEVELS]).slice().sort((a, b) => a - b);
  const sClose = scaleAtClose(input.scale, mtc, session);
  const implied = input.scale.kind === "implied" && Number.isFinite((input.scale as { s0?: number }).s0 ?? Number.NaN) && (input.scale as { s0: number }).s0 > 0;

  // Forward elapsed grid: 0, step, 2*step, ..., mtc (always include the close endpoint).
  const elapsedGrid: number[] = [];
  for (let e = 0; e < mtc; e += step) elapsedGrid.push(e);
  elapsedGrid.push(mtc);

  const coneLevels: ConeLevel[] = levels.map((k) => {
    const kUp = implied ? impliedSideK(k, "up") : k;
    const kDown = implied ? impliedSideK(k, "down") : k;
    return {
      k,
      points: elapsedGrid.map((elapsed) => {
        const sqrtShare = Math.sqrt(varianceShare(mtc, elapsed, session));
        const halfUp = kUp * sClose * sqrtShare;
        const halfDown = kDown * sClose * sqrtShare;
        return {
          elapsedMinutes: elapsed,
          minutesToClose: mtc - elapsed,
          half: 0.5 * (halfUp + halfDown),
          halfUp,
          halfDown,
          upper: input.anchorSpot + halfUp,
          lower: input.anchorSpot - halfDown,
        };
      }),
    };
  });

  const k1Up = implied ? impliedSideK(1, "up") : 1;
  const k1Down = implied ? impliedSideK(1, "down") : 1;
  return {
    anchorSpot: input.anchorSpot,
    anchorMinutesToClose: mtc,
    rate: mtc > 0 ? sClose / Math.sqrt(mtc) : 0,
    // Report the kind that actually drove the math: an "implied" ConeScale with a
    // missing/invalid s0 resolves to the prior — the legend must not claim live IV.
    scaleKind: implied ? "implied" : "prior",
    sAtClose: sClose,
    closeRange: {
      half: 0.5 * (k1Up + k1Down) * sClose,
      upper: input.anchorSpot + k1Up * sClose,
      lower: input.anchorSpot - k1Down * sClose,
    },
    levels: coneLevels,
  };
}

// --- derive ONE day move-scale from the live spreads (the per-day cone width) ---

export type ConeSpreadInput = {
  side: SpreadSide;
  shortStrike: number;
  width?: number;
  creditNow?: number | null;
};

function median(xs: number[]): number {
  const s = xs.slice().sort((a, b) => a - b);
  const mid = Math.floor(s.length / 2);
  return s.length % 2 ? s[mid] : 0.5 * (s[mid - 1] + s[mid]);
}

/**
 * Collapse the on-screen 0DTE spreads to one `ConeScale`: the median of each spread's
 * implied move-scale (reuses spreadResponse.impliedScale — the same vol that drives the
 * P/L curve). Median is robust to one mismarked leg. `aPrior` is passed as NaN so the
 * inversion's internal 1.21·sqrt(mtc) fallback can never masquerade as an implied scale —
 * ill-conditioned credits (near 0 / near width / far-ITM) drop out here and we honestly
 * return the `prior` kind when nothing usable remains.
 */
export function coneScaleFromSpreads(
  spreads: ConeSpreadInput[],
  spot: number,
  minutesToClose: number,
): ConeScale {
  const s0s = spreads
    .filter((s) => s.creditNow != null && Number.isFinite(s.creditNow))
    .map((s) =>
      impliedScale(
        s.creditNow as number,
        signedDistanceToLoss(s.side, spot, s.shortStrike),
        s.width ?? DEFAULT_WIDTH,
        minutesToClose,
        Number.NaN,
      ),
    )
    .filter((x) => Number.isFinite(x) && x > 0);
  if (!s0s.length) return { kind: "prior" };
  return { kind: "implied", s0: median(s0s), sourceMinutesToClose: Math.max(minutesToClose, 0.5) };
}
